version: '3.4'

services:
  interviewquestion.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=intvwdb;Persist Security Info=True;User ID=sa;Password=Passw0rd1!;MultipleActiveResultSets=true
    ports:
      - "5150:80"
      - "7150:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro